/* soapjuangwBindingProxy.cpp
   Generated by gSOAP 2.8.17r from gwserver.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapjuangwBindingProxy.h"

juangwBindingProxy::juangwBindingProxy()
{	juangwBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

juangwBindingProxy::juangwBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

juangwBindingProxy::juangwBindingProxy(const char *url)
{	juangwBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

juangwBindingProxy::juangwBindingProxy(soap_mode iomode)
{	juangwBindingProxy_init(iomode, iomode);
}

juangwBindingProxy::juangwBindingProxy(const char *url, soap_mode iomode)
{	juangwBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

juangwBindingProxy::juangwBindingProxy(soap_mode imode, soap_mode omode)
{	juangwBindingProxy_init(imode, omode);
}

juangwBindingProxy::~juangwBindingProxy()
{ }

void juangwBindingProxy::juangwBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://gw.msndvr.com/gwsvr/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void juangwBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void juangwBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	juangwBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void juangwBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *juangwBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *juangwBindingProxy::soap_fault()
{	return this->fault;
}

const char *juangwBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *juangwBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int juangwBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int juangwBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void juangwBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void juangwBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *juangwBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int juangwBindingProxy::deviceOnServer(const char *endpoint, const char *soap_action, std::string Id, struct ns1__deviceOnServerResponse &_param_1)
{	struct soap *soap = this;
	struct ns1__deviceOnServer soap_tmp_ns1__deviceOnServer;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://gw.msndvr.com/gwsvr/gwserver.php";
	if (soap_action == NULL)
		soap_action = "http://gw.msndvr.com/gwsvr/deviceOnServer";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_ns1__deviceOnServer.Id = Id;
	soap_serializeheader(soap);
	soap_serialize_ns1__deviceOnServer(soap, &soap_tmp_ns1__deviceOnServer);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deviceOnServer(soap, &soap_tmp_ns1__deviceOnServer, "ns1:deviceOnServer", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deviceOnServer(soap, &soap_tmp_ns1__deviceOnServer, "ns1:deviceOnServer", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns1__deviceOnServerResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__deviceOnServerResponse(soap, &_param_1, "ns1:deviceOnServerResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
